dubins_radius: 20
# no dubins is same as step_size equals half the minimum distance between the csv's waypoints
dubins_step_size: 1
handover_offs: 1 # Meters before the end of the path to handover control of the vehicle
lookahead: 8  # Distance to look ahead to select next target waypoint when in need to replan. It is not lookahead of ILOS.
ilos_lookahead: 6
replan_dist: 26
no_of_laps: 2
sim_enable: true
max_speed         : 0.3
min_speed         : 0.1
goal_lat          : -33.722765834294044
goal_lon          : 150.67398711024646
goal_head         : 1.5
# kp makes it faster
# kd reduces overshoot
# ki reduces settling error
kp                : 1 # 5s to get to overshoot (that's the fastest you can get)
kd                : 7 # 10 (20s to get to 3° error) 7 (~25s to 3°) (7 has less overshoot)
ki                : 0.5 
#fw_speed: 0

lookahead     : 5  # meters
lookahead_min : 5     # meters
lookahead_max : 5    # meters
conv_rate     : 8.0   
gamma         : 0.015  # integral gain 


mission: 'Meredith/mission.csv'