mode: real
use_sim_time: false

origin:
  lat: null
  lon: null

model_name: blueboat

boat:
  max_thrust_N: 250.0
  sim_thrust_scale: 1.0

topics:
  gps: /wamv/sensors/gps/gps/fix
  imu: /wamv/sensors/imu/imu/data
  ground_truth_odometry: /molo_boat/estimated_odometry
  left_thrust: /pwm/left_thrust_cmd
  right_thrust: /pwm/right_thrust_cmd
  lidar_points: /rslidar_points
  lidar_points_filtered: /rslidar_points/filtered
  lidar_imu: /rslidar_imu_data
  zed_rgb_image: /zed/zed/rgb/color/rect/image
  zed_rgb_camera_info: /zed/zed/rgb/color/rect/camera_info
  zed_point_cloud: /zed/zed/point_cloud/cloud_registered
