# ===============================================================
# Depth pipeline configuration
# Each field matches the argparse arguments for the depth pipeline
# ===============================================================

depth_pipeline:

  encoder: vitl                # (str) options: [vits, vitb, vitl, vitg], default='vitl'
  # (str, required) path to depth model weights
  load_from: "/workspace/codebase/mini-bream/src/ros2_ws/src/mission_planner/mission_planner/moloplanner/dependencies/Depth-Anything-V2/checkpoints/metric_depth/depth_anything_v2_metric_hypersim_vitl.pth"
  max_depth: 20.0              # (float) maximum predicted depth, default=20.0
  # (str, required) SAM2 checkpoint path
  sam2_checkpoint: "/workspace/codebase/mini-bream/src/ros2_ws/src/mission_planner/mission_planner/moloplanner/dependencies/sam2/checkpoints/sam2.1_hiera_large.pt" 
  # (str, required) SAM2 model config path
  sam2_model_cfg: "configs/sam2.1/sam2.1_hiera_l.yaml"  
  # (str, required) image file, directory, or glob pattern
  img_path: "/workspace/codebase/mini-bream/src/ros2_ws/src/mission_planner/mission_planner/moloplanner/assets/input_imgs"    
  # (str) directory to save inference results, default='./vis_pointcloud'
  outdir: "/workspace/codebase/mini-bream/src/ros2_ws/src/mission_planner/mission_planner/moloplanner/assets/output_dir/depth_pipeline"   
  focal_length_x: 1580.29      # (float) camera calibration parameter, default=1580.29
  focal_length_y: 1581.78      # (float) camera calibration parameter, default=1581.78
  # Enable specific results' saving (saves to 'outdir')
  pred_only: true             # (bool) only save depth prediction, default=false
  save_pcl: true              # (bool) save pointcloud to .ply file, default=false
  plot_summary: true          # (bool) save summary image (depth + mask + BEV), default=false
  grayscale: true             # (bool) disable color palette, default=false
  write_singles: true         # (bool) write intermediate module images, default=false

astart_planner:
  outdir: "/workspace/codebase/mini-bream/src/ros2_ws/src/mission_planner/mission_planner/moloplanner/assets/output_dir/astart_planner_part3"
  save_output: true

moloplanner:
  bev_inpainted_dir: "/workspace/codebase/mini-bream/src/ros2_ws/src/mission_planner/mission_planner/moloplanner/assets/BEV_inpainted_ks_10_square"
  pcds_path: "/workspace/codebase/mini-bream/src/ros2_ws/src/mission_planner/mission_planner/moloplanner/assets/BEV_inpainted_ks_10_square/as_pcl/"
  bevs_npy: "/workspace/codebase/mini-bream/src/ros2_ws/src/mission_planner/mission_planner/moloplanner/assets/BEV_inpainted_ks_10_square/bev_binary_as_npy/"
